### ISSUE TITLE
How about using double quoting when referencing variables.

### ISSUE THREAD

**Issue by taeguk** [HaebinShin/AutoGrader#4]
Double quoting is not used now in some references of variables.
Using double quoting in referencing string type variables is more safe and advisable.

**Comment by HaebinShin** [comment]
That's why i fixed it like c252c7e1b19fb609b1b9f396d1a1c0fcf794c6e1
But i just did it for parameter variable. 
Good advise. Thanks!!

d8c77584203dd7c47e06663a6b8b1df4c6e1f156

**Comment by taeguk** [comment]
Good nogada :)
